[package]
name = "openloong_sdk_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
log = "0.4.27"
ndarray = "0.16.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
