[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
openloong_sdk_rust = { path = "../../openloong_sdk_rust" }
log = "0.4.27"
ndarray = "0.16.1"
tokio = { version = "1.45.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
